# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='475', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='464', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='%Y/%m/%d/', width_field='image_width'),
        ),
    ]
