# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='featured_post',
            field=models.CharField(choices=[('1', 'green'), ('2', 'red')], max_length=256),
        ),
    ]
