# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160613_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='featured_post',
            field=models.CharField(choices=[('featured', 'Featured Post'), ('not', 'Not Featured')], default='not', max_length=256),
        ),
    ]
