# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category_post',
            old_name='post_id',
            new_name='post',
        ),
    ]
